services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: MySQLShopdb
    ports:
      - 3306:3306

  app:
    image: anna228322/spring-app
    environment:
      JDBC_URL: jdbc:mysql://db/MySQLShopdb
      DB_USER: root
      DB_PASSWD: 123
    depends_on:
      - db
    ports:
      - 8080:8080